master:
  image: elasticsearch:v0.01
  ports:
     - "9200:9200"
  restart: always
  container_name: esmaster

esnode:
  image: elasticsearch:2.2.1
  command: elasticsearch --discovery.zen.ping.unicast.hosts=master
  restart: always
  links:
    - master
#
# esnode2:
#   image: elasticsearch:2.2.1
#   command: elasticsearch --discovery.zen.ping.unicast.hosts=esmaster
#   restart: always
#   links:
#     - master
