master:
  image: dmanchon/elasticsearch:v0.2
  ports:
     - "9200:9200"
  restart: always
  container_name: esmaster
  mem_limit: 1000000000
  cpu_shares: 100

esnode:
  image: dmanchon/elasticsearch:v0.2
  command: elasticsearch --discovery.zen.ping.unicast.hosts=master
  restart: always
  links:
    - master
  mem_limit: 1000000000
  cpu_shares: 100
